[profile.default]
src = "src"
out = "out"
libs = ["lib", "dependencies"]

[dependencies]
forge-std = "1.12.0"
eth-infinitism-account-abstraction = "0.6"
"@openzeppelin-contracts" = "4.2.0"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

[rpc_endpoints]
local = "http://127.0.0.1:8545"
